# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inv_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=15)),
                ('locationAddress', models.CharField(max_length=50)),
                ('statusId', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'inv_location',
            },
        ),
        migrations.CreateModel(
            name='inv_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_status',
            },
        ),
        migrations.CreateModel(
            name='inv_warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(max_length=15)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status')),
            ],
            options={
                'db_table': 'inv_warehouse',
            },
        ),
    ]
