# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp_jobrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobRole', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'emp_jobrole',
            },
        ),
        migrations.CreateModel(
            name='emp_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'emp_location',
            },
        ),
        migrations.CreateModel(
            name='family_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=8)),
                ('DateOfBirth', models.DateField(max_length=8)),
                ('Relationship', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'family_details',
            },
        ),
        migrations.CreateModel(
            name='inv_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=15)),
                ('locationAddress', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inv_location',
            },
        ),
        migrations.CreateModel(
            name='inv_materialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialCategory', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inv_materialCategory',
            },
        ),
        migrations.CreateModel(
            name='inv_materialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialType', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_materialType',
            },
        ),
        migrations.CreateModel(
            name='inv_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_position',
            },
        ),
        migrations.CreateModel(
            name='inv_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productNo', models.CharField(max_length=50, null=True)),
                ('productName', models.CharField(max_length=100)),
                ('productDescription', models.CharField(blank=True, max_length=250, null=True)),
                ('productModel', models.CharField(blank=True, max_length=100, null=True)),
                ('productCompany', models.CharField(blank=True, max_length=100, null=True)),
                ('productPackage', models.CharField(blank=True, max_length=100, null=True)),
                ('productPurchasable', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productPurchaseListPrice', models.IntegerField(default=0)),
                ('productPriceTolerancePercent', models.IntegerField(default=0)),
                ('productSellable', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productSerialControlled', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productBatchTracked', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('standardCost', models.IntegerField(default=0)),
                ('reorderLevel', models.IntegerField(default=0)),
                ('reorderQty', models.IntegerField(default=0)),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialCategory')),
                ('productType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialType')),
            ],
            options={
                'db_table': 'inv_products',
            },
        ),
        migrations.CreateModel(
            name='inv_quantity',
            fields=[
                ('quantityId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('locationId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location')),
                ('positionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_position')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
            ],
            options={
                'db_table': 'inv_quantity',
            },
        ),
        migrations.CreateModel(
            name='inv_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'inv_status',
            },
        ),
        migrations.CreateModel(
            name='inv_UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurementName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_UnitOfMeasure',
            },
        ),
        migrations.CreateModel(
            name='inv_warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(max_length=15)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status')),
            ],
            options={
                'db_table': 'inv_warehouse',
            },
        ),
        migrations.CreateModel(
            name='jts_departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'jts_departments',
            },
        ),
        migrations.CreateModel(
            name='jts_employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=25)),
                ('userName', models.CharField(max_length=25)),
                ('emailId', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=7)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('dateOfBirth', models.DateField(max_length=8)),
                ('dateOfJoining', models.DateField(auto_now_add=True, null=True)),
                ('dateOfExit', models.DateField(blank=True, default=None, max_length=8, null=True)),
                ('departmentId', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('managerId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='InventoryApp.jts_employees')),
                ('reportingHr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_hr', to='InventoryApp.jts_employees')),
                ('workLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_location')),
            ],
            options={
                'db_table': 'jts_employees',
            },
        ),
        migrations.CreateModel(
            name='jts_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'jts_products',
            },
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseQuantity', models.IntegerField()),
                ('jts_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_products')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
            ],
            options={
                'db_table': 'production',
            },
        ),
        migrations.CreateModel(
            name='requisition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisitionDate', models.DateField(auto_now_add=True, null=True)),
                ('duedate', models.DateField(max_length=8)),
                ('productCategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialCategory')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees')),
            ],
            options={
                'db_table': 'requisition',
            },
        ),
        migrations.CreateModel(
            name='requisition_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityRequested', models.IntegerField(default=0)),
                ('quantityIssued', models.IntegerField(default=0)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
                ('requisitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.requisition')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status')),
            ],
            options={
                'db_table': 'requisition_details',
            },
        ),
        migrations.CreateModel(
            name='user_menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=30)),
                ('jobRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_jobrole')),
            ],
            options={
                'db_table': 'user_menus',
            },
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_jobrole')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='jts_departments',
            name='departmentHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees'),
        ),
        migrations.AddField(
            model_name='inv_quantity',
            name='warehouseId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse'),
        ),
        migrations.AddField(
            model_name='inv_products',
            name='productUOM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='inv_products',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
        migrations.AddField(
            model_name='inv_position',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
        migrations.AddField(
            model_name='inv_position',
            name='warehouseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse'),
        ),
        migrations.AddField(
            model_name='inv_location',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
        migrations.AddField(
            model_name='family_details',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees'),
        ),
    ]
