# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
