# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='family_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=8)),
                ('DateOfBirth', models.DateField(max_length=8)),
                ('Relationship', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'family_details',
            },
        ),
        migrations.CreateModel(
            name='jts_departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'jts_departments',
            },
        ),
        migrations.CreateModel(
            name='jts_employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=25)),
                ('userName', models.CharField(max_length=25)),
                ('emailId', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=250)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHERS', 'others')], max_length=7)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('dateOfBirth', models.DateField(max_length=8)),
                ('dateOfJoining', models.DateField(default=datetime.date.today, max_length=8)),
                ('dateOfExit', models.DateField(blank=True, default=None, max_length=8, null=True)),
                ('departmentId', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('jobRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_jobrole')),
                ('managerId', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='InventoryApp.jts_employees')),
                ('reportingHr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_hr', to='InventoryApp.jts_employees')),
                ('workLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_location')),
            ],
            options={
                'db_table': 'jts_employees',
            },
        ),
        migrations.AddField(
            model_name='jts_departments',
            name='departmentHead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees'),
        ),
        migrations.AddField(
            model_name='family_details',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees'),
        ),
    ]
