# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0003_auto_20180123_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='requisition_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=10)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
                ('requisitionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.requisition')),
            ],
            options={
                'db_table': 'requisition_details',
            },
        ),
    ]
