# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_requisition_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition_details',
            old_name='Quantity',
            new_name='quantityRequested',
        ),
        migrations.AddField(
            model_name='requisition',
            name='statusId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
        migrations.AddField(
            model_name='requisition_details',
            name='quantityIssued',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
