# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0006_auto_20180124_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='inv_materialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialCategory', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'inv_materialCategory',
            },
        ),
        migrations.CreateModel(
            name='jts_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'jts_products',
            },
        ),
        migrations.CreateModel(
            name='production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseQuantity', models.IntegerField()),
                ('jts_products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_products')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
            ],
        ),
    ]
