# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0007_inv_materialcategory_jts_products_production'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='production',
            table='production',
        ),
    ]
