# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0008_auto_20180126_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_products',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialCategory'),
        ),
        migrations.AddField(
            model_name='requisition',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialCategory'),
        ),
    ]
