# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0009_auto_20180126_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.emp_jobrole')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.jts_employees')),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
    ]
