# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0010_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityIssued',
            field=models.IntegerField(default=0),
        ),
    ]
