# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-03 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0012_user_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_status',
            name='statusName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='statusId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
