# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0013_auto_20180203_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='inv_quantity',
            fields=[
                ('quantityId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('locationId', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location')),
                ('positionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_position')),
            ],
            options={
                'db_table': 'inv_quantity',
            },
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPriceTolerancePercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPurchaseListPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialType'),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productUOM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='reorderLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='reorderQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='standardCost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityRequested',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inv_quantity',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products'),
        ),
        migrations.AddField(
            model_name='inv_quantity',
            name='warehouseId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse'),
        ),
    ]
