# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0013_auto_20180203_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='inv_quantity',
            fields=[
                ('quantityId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('locationId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location')),
                ('positionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_position')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_products')),
                ('warehouseId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse')),
            ],
            options={
                'db_table': 'inv_quantity',
            },
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityRequested',
            field=models.IntegerField(default=0),
        ),
    ]
