# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0014_auto_20180210_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_products',
            name='productPriceTolerancePercent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPurchaseListPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialType'),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productUOM',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='reorderLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='reorderQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='standardCost',
            field=models.IntegerField(default=0),
        ),
    ]
