# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0015_auto_20180210_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
