# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0015_auto_20180210_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_quantity',
            name='locationId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location'),
        ),
        migrations.AlterField(
            model_name='inv_quantity',
            name='warehouseId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse'),
        ),
    ]
