# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0016_auto_20180210_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inv_products',
            name='productCompany',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productModel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPackage',
            field=models.CharField(max_length=100),
        ),
    ]
