# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0016_auto_20180215_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityIssued',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityRequested',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default='5', on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
