# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0017_auto_20180215_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityIssued',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityRequested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='statusId',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
