# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0017_auto_20180212_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='inv_products',
            name='productNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productCompany',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productDescription',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productModel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPackage',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
