# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0018_auto_20180215_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityIssued',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requisition_details',
            name='quantityRequested',
            field=models.IntegerField(default=0),
        ),
    ]
