# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0019_auto_20180215_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jts_employees',
            name='jobRole',
        ),
        migrations.AddField(
            model_name='inv_products',
            name='productNo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productCompany',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productDescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productModel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inv_products',
            name='productPackage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inv_quantity',
            name='locationId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_location'),
        ),
        migrations.AlterField(
            model_name='inv_quantity',
            name='warehouseId',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse'),
        ),
    ]
