# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 14:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0002_auto_20171202_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='inv_materialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialType', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_materialType',
            },
        ),
        migrations.CreateModel(
            name='inv_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=15)),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status')),
                ('warehouseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_warehouse')),
            ],
            options={
                'db_table': 'inv_position',
            },
        ),
        migrations.CreateModel(
            name='inv_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productDescription', models.CharField(max_length=250)),
                ('productModel', models.CharField(max_length=50)),
                ('productCompany', models.CharField(max_length=20)),
                ('productPackage', models.CharField(max_length=15)),
                ('productPurchasable', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productPurchaseListPrice', models.CharField(max_length=10)),
                ('productPriceTolerancePercent', models.CharField(max_length=10)),
                ('productSellable', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productSerialControlled', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('productBatchTracked', models.CharField(choices=[('YES', 'yes'), ('NO', 'no')], default='YES', max_length=5)),
                ('standardCost', models.CharField(max_length=10)),
                ('reorderLevel', models.CharField(max_length=10)),
                ('reorderQty', models.CharField(max_length=15)),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_materialType')),
            ],
            options={
                'db_table': 'inv_products',
            },
        ),
        migrations.CreateModel(
            name='inv_UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurementName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'inv_UnitOfMeasure',
            },
        ),
        migrations.AddField(
            model_name='inv_products',
            name='productUOM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='inv_products',
            name='statusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryApp.inv_status'),
        ),
    ]
