# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0004_auto_20180112_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jts_employees',
            name='managerId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='InventoryApp.jts_employees'),
        ),
        migrations.AlterField(
            model_name='jts_employees',
            name='reportingHr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporting_hr', to='InventoryApp.jts_employees'),
        ),
    ]
