# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0005_auto_20180113_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jts_employees',
            name='statusId',
        ),
    ]
